### ISSUE TITLE
Incorrect fill tessellation with some complex paths.

### ISSUE THREAD

**Issue by fschutt** [nical/lyon#140]
I use this library for GIS / spatial purposes. It's not perfect, but it works somewhat. One thing is that coordinates often have a very high precision. It would be nice to have `lyon::path::Path::points()` be generic over the input type (f32, f64, etc.).

Just an idea.

**Comment by nical** [comment]
Do you mean, having only the `Path` data structure generic? This shouldn't be too hard to implement, but it wouldn't be able to use the goodies in path_iterator/path_builder without a lot of extra work (but maybe that's enough for what you need?).
Making tessellators (especially fill) generic over the scalar type would make too much of a mess in code that is already quite complex.

**Comment by sharazam** [comment]
My actual problem is that lyon sometimes fails to handle complex polygons (especially with concave shapes). So I thought this problem might be related to accuracy. Maybe it's not. See below - green, my tesselation with lyon, violet: QGIS - actual, correct tesselation:

![lyon_wrong](https://user-images.githubusercontent.com/12084016/29315298-be597ed2-81c2-11e7-89ba-b34a3c3ee828.png)

I thought this might have something to do with accuracy, but I think I may be wrong.

**Comment by nical** [comment]
Ah! Interesting, so this is indeed a precision bug, but not necessarily one that would be fixed moving to double precision floats (most likely the bug would still exist but would be harder to reproduce). Internally, the tessellator works with 16.16 fixed point numbers anyway.
I am going to put together a way to easily serialize paths into the svg syntax. Once we have that handy, it would help if you could give me a path that is showing this bug as well as a screenshot of what the correct shape looks like so that I can investigate the problem.

**Comment by sharazam** [comment]
Just fyi: Mapbox has a library for triangulation, written in JS: https://github.com/mapbox/earcut

They have a lot of test files (JSON): https://github.com/mapbox/earcut/tree/master/test/fixtures

Could be easily serialized via serde-json or similar.

**Comment by nical** [comment]
@sharazam I published version 0.7.2 with a fix in the tessellator that fixed most of the failing tests. Could you try again and see if the bug still reproduces? I it does, it would help if you could extract a test case for me to investigate. I added `lyon::svg::serializer::PathSerializer` which builds a `String` using the SVG path syntax.

**Comment by sharazam** [comment]
You did not publish it, at least I can't see it on crates.io (still 0.7.1 for me). I used the `{ git = "..." }`. I'm sorry to say, but it's the same result as before:

![pic_wrong_lyon](https://user-images.githubusercontent.com/12084016/29494315-c40f2096-85a7-11e7-9285-e7fe7552da52.png)


Plus you left a comment in there: `test intersections: false false`, which appears a few thousand times.
I'll give you a test application, maybe it's just something with my code. Thanks for taking the time to do this.

**Comment by nical** [comment]
Oops! The printlns are fixed in 0.7.3, properly published this time.

**Comment by sharazam** [comment]
@nical I have reproduced the issue here: https://github.com/sharazam/lyon-testcase-openstreetmap

You can use mouse click + drag to pan the map and scrolling to zoom.

Maybe it's just my wrong indexing, I don't know. Features in the map are nested, so I build a path for each polygon (which may be wrong because of missing holes, but this could be done later). The data is from the JSON file, but I've also added it as an SVG, a shapefile and a tiff rendering.

**Comment by nical** [comment]
Thanks a lot! I'll have a look as soon as I can.

**Comment by fschutt** [comment]
any progress? just asking.

**Comment by nical** [comment]
I haven't had time to delve into this enough to make progress yet (other than to quickly verify that it is indeed a bug in the tessellator). I'll need to figure out some kind of tool to debug this or isolate the issue somehow.
In any case I really want to figure this problem out.

**Comment by nical** [comment]
@fschutt I found the problem :) The test case is actually tessellated properly, but the rendering code uses triangle strips instead of triangle lists! So things should be fine as soon as you change to using `PrimitiveType::TrianglesList` when creating your index buffer. I realize that nowhere in the docs did I explain what kind of primitives to use to render the tessellation, I need to address that.

After you have tested the change, please let me know if the problem is gone to confirm.

**Comment by nical** [comment]
I am not 100% certain the tessellation is correct (some holes appear to be missing compared to the picture from one of your first comments), but there's a big improvement for sure.

**Comment by fschutt** [comment]
Yup, that was it, thanks! I suspected something with the indexing was wrong, but couldn't figure out what it was. 

The missing holes are probably my fault, but I am not sure how to handle these (i.e. how to tell lyon that these are actually holes). Do I just plug in the points in reverse order or are they marked with a special flag? However, there are still some issues and this time I think it's due to precision:

![image](https://user-images.githubusercontent.com/12084016/29950103-d93d7268-8eb9-11e7-8356-544078a852fb.png)

![image](https://user-images.githubusercontent.com/12084016/29950161-337c4010-8eba-11e7-9a3f-774e97d87160.png)

![image](https://user-images.githubusercontent.com/12084016/29950196-6d0796cc-8eba-11e7-9685-d4cbdccf958d.png)

And:

![image](https://user-images.githubusercontent.com/12084016/29950209-879d3c6c-8eba-11e7-91b1-106d5e47821a.png)

![image](https://user-images.githubusercontent.com/12084016/29950251-c7386270-8eba-11e7-942e-6ab6764c28b0.png)

![image](https://user-images.githubusercontent.com/12084016/29950217-9b4ba032-8eba-11e7-9363-6c3c40400e74.png)

Even if the holes aren't handled, they should not affect the other polygons, since each polygon is processed individually. But yes, it's a lot better than the previous pictures. I'd leave this bug open, because I don't know what's causing this. Notice that this is actually one big polygon with a hole, not two seperate polygons. These bugs are in the lower left corner of the data.

To debug, you can add `draw_options.polygon_mode = glium::draw_parameters::PolygonMode::Line;` to the `draw_options`, then the polygons are rendered with GL_LINES.

I also found it weird that the holes do not show up at all - I'd expect them to actually show up as filled polygons, even though they are not holes. Or is this an optimization thing - do overlapped polygons get optimized out?

The data is missing the relevant info to tell if a polygon is a hole or not. I'll update the repository tomorrow to add this info.

**Comment by nical** [comment]
For holes you just need to draw a sub-path inside another sub-path within the same path (when using the [EvenOdd fill rule](https://www.w3.org/TR/SVG/painting.html#FillProperties) which is the only one supported at the moment):

```rust
// path begins here
builder.move_to(point(0.0, 0.0)); // <- 1st sub-path begins here
builder.line_to(point(10.0, 0.0));
builder.line_to(point(10.0, 10.0));
builder.close();
builder.move_to(point(2.0, 2.0)); // <- 2nd sub-path begins here
builder.line_to(point(4.0, 2.0));
builder.line_to(point(4.0, 4.0));
builder.close();
let path = builder.build(); // path ends here
```

The code above will end up tessellating a triangle with a triangular hole inside of it.

**Comment by nical** [comment]
The areas you showed in the last pictures render correctly for me in your test case when the index buffer is using triangle lists.

**Comment by fschutt** [comment]
> The areas you showed in the last pictures render correctly for me in your test case when the index buffer is using triangle lists.

Hmm .. I can't get it to work this way. I use the index buffer that I got back from `lyon` with `PrimitiveType::TrianglesList` as the type and the rendering issues show up. If I use an empty index buffer, it doesn't work either. Can you do a PR to the `lyon-testcase` repository, so I can see what buffer you were using? If it renders correctly, that's great, I just want to test this. Thanks.

Is this only the last image or the others, too?

**Comment by fschutt** [comment]
Alright, this seems to have to do something else with my code then, not the actual tesselator. I'll leave the repository up, it renders correctly now. Sorry for wasting so much time over a simple fix.

**Comment by nical** [comment]
> Sorry for wasting so much time over a simple fix.

Not at all! You pointed me to the earcut tests which got me to improve testing and fix two important bugs in the tessellator [(1)](https://github.com/nical/lyon/commit/c30fb0668bcfc67f791ff2c071dcd5d09b2b0bbc), [(2)](https://github.com/nical/lyon/commit/ac411df7bbc8cab22d185c7c8e047bf8c159f091) even though they were not related to this particular issue. So I am genuinely happy about the outcome here :)
Also I'm glad that to see lyon used in projects and I'm happy to help.
