### ISSUE TITLE
Render text along path

### ISSUE THREAD

**Issue by ifeherva** [nical/lyon#163]
Hi, I am working on a rust library that needs to render text with a given font along a given path. Is this possible with lyon?

Thanks

**Comment by nical** [comment]
Hi, lyon does not have any text rendering primitives at the moment (the focus is on filling and stroking paths). However you may find some of the stuff in the [lyon_bezier](https://docs.rs/lyon_bezier/*/lyon_bezier/) crate useful. In particular the flattening algorithm is the same as the one Firefox uses to measure the distance along paths which is needed when rendering text along a path to position the glyphs. That's just a piece of the puzzle, though.

**Comment by nical** [comment]
@ifeherva #254 got merged which introduces the possibility to "walk" along a path instead of iterating over its segments end points. This makes it easy to *position* and orient glyphs along a path even with variable space between glyphs. Lyon does not have any text rendering infrastructure, so if you want to make use of this you still need your own glyph rendering code.

If this turns out to be useful, you can use it and only depend on the lyon_path crate (the version that contains this feature has not been published on crates.io yet though), without depending on all of the tessellators, etc.

![screenshot](https://raw.githubusercontent.com/nical/lyon/master/examples/walk_path/screenshot.png)

Closing the issue since text rendering isn't going to happen in the near future.

**Comment by ifeherva** [comment]
Thanks a lot, I will definitely take a look into it.
