### ISSUE TITLE
Automatically position the view in the command line show command.

### ISSUE THREAD

**Issue by nical** [nical/lyon#203]
It would be great if the command line tool's `show` sub-command would position the camera automatically.

To do that we just need to approximate the bounding box of the path and move the camera to the center of the bounding box.

The command-line tool is the program under the `cli/` directory, and the show command is implemented in `cli/src/show.rs`.

**Comment by V1shvesh** [comment]
Can I work upon this??

**Comment by nical** [comment]
@V1shvesh absolutely! thanks for chiming in!
Don't hesitate to ask any question, if there is anything I can do to help with navigating through the code, etc.

**Comment by V1shvesh** [comment]
I'm having trouble compiling the cli
Can you tell me how can I do that?

**Comment by o0Ignition0o** [comment]
When at the root directory you can run ` cargo build ` to build the whole project (including the cli)

If you want to run the cli you can go to the cli directory and run an example : 

`$ cd cli                                            
$ cargo run -- show "M0 15 l5 5 l -3 -5 Z" -fs --line-join MiterClip                                                                                                                      `

this should display a small shape in the middle of a window, and you can press pageUp/pageDown to adjust the zoom :)

**Comment by nical** [comment]
In addition to what @o0Ignition0o said, you can also go directly to the cli directory and run the command `cargo build` from there to build if it is more convenient.
Also if if you want to a more advanced path to test with you can (also from the cli directory) run `cargo run -- show -i ../assets/logo.path -fs` (the `-i <file>` parameter lets you load from a file instead of writing the path in the command line and there is an example path in `assets/logo.path`).

**Comment by V1shvesh** [comment]
I'm sorry, I've been away too long.
I've figured out how to run it, and the current problem I have is how to approximate the bounding box, well in general, how to go about the problem.
Can you guys please assist me with this??

**Comment by o0Ignition0o** [comment]
Hey :) DW there's no rush :)
Now that you can run it, one way would be to figure out how to compute a "bounding rectangle" which would enclose the shape, to figure out what the window could look like. Since you draw the shape you could figure out all the "event points " and also a x min/max and a y min/max.
The next step would be centering the window to this rectangle and zooming in an appropriate way !
Cheers you can do it ! If you have any question don't hesitate to ask :)

**Comment by o0Ignition0o** [comment]
Having absolute and relative "move to" commands should allow you to track where the scene takes place, give it a try :)

**Comment by o0Ignition0o** [comment]
hey @V1shvesh , I gave it an other thought, and after a tessellation you get vertice positions : 

` target/debug/lyon tessellate "M 0 0 L 10 0  10 10 L 0 10 z"                                                                                                                                0|10:07:47
vertices: [(0, 0), (10, 0), (0, 10), (10, 10)]
indices: [0, 1, 2, 2, 1, 3]
 ` 
The vertices should allow you to compute the "min and max X and Y positions", hence the scene borders :)

**Comment by o0Ignition0o** [comment]
Hey :) I had to do something a bit similar to what I advised in order to prepare an other Pull Request : https://github.com/o0Ignition0o/lyon/blob/9fd475f44db5baaa8929529c092488dea1f24f6c/cli/src/export.rs#L234 

Maybe this will help you, and I'll use your set of functions instead once you're done ! :)

**Comment by nical** [comment]
@V1shvesh Oops sorry I forgot you had been looking into this, the feature is implemented now.
