### ISSUE TITLE
Panic on self intersecting polygons with many vertices

### ISSUE THREAD

**Issue by turnage** [nical/lyon#291]
If I call basic_shapes::fill_polyline with a self intersecting polygon with 2560 randomly placed vertices, I panic at [path_fill.rs](https://github.com/nical/lyon/blob/0011f6c8905413841c1abd6e6686a6a1c2b19dd4/tessellation/src/path_fill.rs#L617) (not always this line but most frequently here) about 1 out of 3 invocations. I found that get the same panic with 80 randomly placed vertices in about 1 out of 1240 invocations (each input being unique).

I'm not 100% sure this isn't a problem on my end yet but I need to solve this, will have a day or two to throw at it soon, and wanted to post in case you had some guidance.

This is a small example; does this look like it ought to work?

```rust
    #[test]
    fn works() {
        use lyon;
        use rand::{Rng, StdRng};
        use lyon::tessellation::*;
        use lyon::tessellation::geometry_builder::{VertexBuffers, simple_builder};
        use lyon::path_builder::math::Point;


        let n = 2560;
        let mut rng = StdRng::new().expect("");
        let verts = (0..n).into_iter().map(|_| -> Point {Point::new(rng.gen(),rng.gen()) });
        let mut buffer: VertexBuffers<FillVertex> = VertexBuffers::new();
        basic_shapes::fill_polyline(
            verts,
            &mut FillTessellator::new(),
            &FillOptions::default(),
            &mut simple_builder(&mut buffer));
    }
```

**Comment by o0Ignition0o** [comment]
Hey, and thanks for posting this issue :)
I tried to run your test ~20 times and I didn't get any error. 
Could you please provide me a back/stasktrace or maybe a panic message?  
Thanks a lot !

**Comment by nical** [comment]
This issue is caused by an accumulation of floating point inaccuracies eventually breaking the algorithm. I can also be reproduced by running the fuzzer in the cli app for a while (it does something similar to your test).

I spent quite a bit of time chasing this type of bug and got the algorithm to be fairly robust for realistic inputs (I mean something that comes from an artist rather than a (potentially malicious) script. It's a never ending battle, though, so my next steps are (in no particular order):

- Making the current tessellator detect and return an error instead of panicking.
- Working on another tessellation algorithm that is designed specifically around the floating-point precision horror show. This new tessellator would rely less on the accumulated state of the algorithm and recover more easily from inaccuracy (with potentially small incorrect pieces near the place where the current one would panic.
- Maybe improving the current tessellator so that floating point inaccuracies [don't accumulate](https://github.com/nical/lyon/issues/243).

**Comment by turnage** [comment]
I see. Thank you for the quick response!

Interestingly stroke tessellation has no problems with these polygons at all.

In the meantime I've created a [wrapper for libtess2](https://github.com/turnage/tess2) just to handle these cases.

**Comment by nical** [comment]
The stroke tessellator is a much much simpler algorithm that doesn't even care about intersections, so it shouldn't have this type of issue. Thanks for setting up libtess2 bindings, I have been meaning to do this for a while in order to have something to compare lyon against.

**Comment by nical** [comment]
Fixed in the new tessellator that just made it into the master branch. Release coming soon.
