### ISSUE TITLE
lyon_geom: Incorrect conversion from arcs to quadratic béziers.

### ISSUE THREAD

**Issue by RazrFalcon** [nical/lyon#318]
I'm trying to use `lyon` in my project and I have troubles with segments conversion.

Here is my experimental code:
https://github.com/RazrFalcon/libresvg/blob/lyon-test/src/convert/path.rs#L150..L171

AFAIU, I have to:
1. create `SvgArc`
1. use `to_quadratic_beziers`
1. convert Quad to Cubic

But it doesn't work (result are incorrect). I think my problem is in previous/from coordinates.

PS: the commented code below is my own implementation, which works fine, but I want to get rid of it.

**Comment by nical** [comment]
Thanks for filing this. The arc-to-bézier (and cubic-to-quadratic approximations) code isn't as well tested as it should be because right now most of lyon directly flattens curves. That's a poor excuse but it explains how issues might have gone unnoticed in this area, I'll have a when I have a bit of time after FOSDEM.

**Comment by RazrFalcon** [comment]
I see. I thought that the problem is on my side.

**Comment by RazrFalcon** [comment]
As for the test cases, here is [a good test file](https://github.com/RazrFalcon/libresvg/blob/master/tests/images/svg/paths-data-03-f.svg), that has a lot of different arc.

**Comment by nical** [comment]
I just fixed a pretty bad bug in the arc to quadratic bézier approximation. I need to do more testing but this is probably the source of most of the issues you were having. I'll dig some more to see if there are other problems.
That said I should add an arc to cubic approximation using the same approach, it would be more useful for what you want to do.

**Comment by RazrFalcon** [comment]
It became a bit better, but still far off.

Expected:
![1](https://user-images.githubusercontent.com/725494/35826409-546db55a-0ac1-11e8-9542-61b47fcc35b1.png)

Actual:
![2](https://user-images.githubusercontent.com/725494/35826423-5f27109a-0ac1-11e8-96dd-87582a7602b6.png)

**Comment by nical** [comment]
Oh wow this is wild! I'll investigate some more using your branch directly to test things.

**Comment by nical** [comment]
Is there a test program that I can run to see this test case with your lyon-test branch?

**Comment by RazrFalcon** [comment]
Yes. [`tools/rendersvg`](https://github.com/RazrFalcon/libresvg/tree/master/tools/rendersvg). [Build instruction](https://github.com/RazrFalcon/libresvg/blob/master/doc/build.md).

**Comment by nical** [comment]
Getting there with #323, but quite done yet:

![out](https://user-images.githubusercontent.com/264854/35869324-13017036-0b5f-11e8-83c0-c2f37c8ad5e5.png)

**Comment by RazrFalcon** [comment]
Good! Is there were any problems in building `resvg`?

**Comment by nical** [comment]
Nope, works like a charm, I'm investigating the remaining issues.

**Comment by nical** [comment]
The remaining issue was simply that I hadn't implemented radius sanitization (if the radii are too small to connect the endpoints they have to be scaled).

The SVG test case now looks a lot better:

![out](https://user-images.githubusercontent.com/264854/35878788-a7ed5876-0b79-11e8-84bf-e890d95f1d06.png)

That said there is one remaining edge case that isn't covered by the arc conversion code, it's when one or both of the radii are equal to zero. In this case the spec say that the arc should be a `line_to` and there isn't a convenient way to represent that in the conversion, so you should first check `svg_arc.is_straight_line()` before calling `to_arc` and handle it there (otherwise you'll get a panic).

**Comment by RazrFalcon** [comment]
Yes, I have this case: https://github.com/RazrFalcon/resvg/blob/dd1394b593eb94064e0c320eb0bd399c5e7c5018/src/convert/path.rs#L220

**Comment by nical** [comment]
We should be done with the arc bugs from this issue now.
