### ISSUE TITLE
lyon_geom: f32 vs f64

### ISSUE THREAD

**Issue by RazrFalcon** [nical/lyon#319]
You are using `f32` for coordinates instead of `f64`. Are there any premises for that? I'm curious because I'm working on SVG libraries and I use `f64` everywhere for no obvious reasons. Is `f32` really enough (at least for coordinates)?

I don't really care about precision or performance, but I'm planning to use `lyon` more and more and constant `f64` <-> `f32` conversions will be painful.

Thanks.

**Comment by nical** [comment]
Thanks to recent contributions by @pizzaiter, lyon_geom is actually the only part of lyon that is generic over the scalar type, and accepts both f32 and f64. However, the rest of lyon only works with f32.

My guess is that the widespread use of 64 bits floats in SVG related software is a bit of a standardisation effect, since SVG files are being produced with high precision numbers you may not want your own tools to lose this existing precision on the files you edit. And while f32 is usually more than enough when working in screen-space or some local object-space coordinate system, Precision can be insufficient if you are in a document-space and do some math very far away from the origin of a huge document.

I believe that f32 is enough for rendering in most cases because you typically work in screen or object space, so in lyon's tessellator I am trying to stick to f32 and use f64 only where I identify the need. For reference, In Firefox we also work mostly with 32 bits floating point arithmetic in the graphics engine, and something that is more or less 32bits fixed point numbers for layout. If we were to produce SVG rather than only consume it I bet we'd want to be more careful about not losing any precision.

I'm happy to hear that you want to use lyon! I am impressed by the work you've done on libresvg/svgparser/etc and I'd love it if lyon could be helpful with that. One direction that lyon could take to make things easier for you might be to make the the [builder](https://docs.rs/lyon_path/0.9.0/lyon_path/builder/index.html) and [iterator](https://docs.rs/lyon_path/0.9.0/lyon_path/iterator/index.html) adapters generic over the scalar type, and provide iterators and builders that do the conversion for you. You could do something like ` let mut path = Path::builder().with_svg().using_f64();` to build a path that is stored in f32 but with f64 in the API, for example.
It's something that I have been thinking about but didn't have a use case for so far.
The natural step after that would be to make the path data structures generic as well.

**Comment by RazrFalcon** [comment]
Thanks for detailed explanation. I don't look into firefox sources, but `cairo` and Qt (mostly) are using double/f64.

I'm closing it now, because it was a question and not a problem.

**Comment by dbrgn** [comment]
Sorry to re-use this issue, but it seems most fitting here.

I also work with SVG and therefore default to using f64 in my data structures. While I can indeed use `euclid::Point2D` with `f64`, this is a type that - in contrast to `lyon_geom::Point` - is not re-exported by lyon.

If using a non-parametrized point in `lyon_geom` is intentional and will stay, maybe you could add that re-export? Or is using `lyon_geom` with f64 an edge case?

(Note: The loss of precision isn't really a problem for me, it's mostly about the bad usability of converting f64 to f32 back and forth all over the codebase.)

**Comment by nical** [comment]
@dbrgn I agree that using the parametrized version of the math types all over `lyon_geom` while not exporting them isn't very intuitive. I think that I'll make the `generic_math` module public so that you can find `lyon_geom::generic_math::Point` just like the f32 version can be found at `lyon_geom::math::Point`.
Note that you can also find the same type at `lyon_geom::euclid::Point2D`.

Some `lyon_` crates such as the tessellation related ones will stick to f32 in the foreseeable future, but the intent is to keeo `lyon_geom` usable with f64 as easily as f32.

**Comment by dbrgn** [comment]
Ah, I wasn't aware that euclid is exposed at `lyon_geom::euclid` :slightly_smiling_face: That helps.

**Comment by nical** [comment]
To be honest, another option I'm considering is to remove the `lyon_geom::math::` reexports and have everything go through `lyon_geom::euclid::` (or reexport all of euclid in lyon_geom, even) since it's not much more effort to type, more clearly shows where the types are coming from and more removes the impression that f32 is favored over f64.

**Comment by dbrgn** [comment]
Yes, I think I'd actually favor that. The reason is that clicking on the type in the docs leads you to euclid anyways, so the `math` module is hard to discover.
