### ISSUE TITLE
Make the project more welcoming and appealing to contributors and users.

### ISSUE THREAD

**Issue by nical** [nical/lyon#32]
Some rust projects have done a stellar job at moving from being a one-person project into being owned and contributed to by a small community built around it. The [gfx crate](https://github.com/gfx-rs/) is a prime example of this.

I would very much like lyon to be more community-driven, so that the project advances faster and in a direction that is useful to more people, and have more people to brainstorm ideas with.

Some ideas off the top of my head:
 - Good documentation: a never ending endeavor, but there has been a lot of work in this area lately.
 - Make lyon easier to use: The tools provided like tessellators are (purposefully) quite low-level and it is a lot of work to use them in any project. Building higher level APIs on top of this could maybe help with being useful for more people? I am experimenting with higher level APIs currently (issue #17).
 - File more issues for newcomers to pick, advertise them in this-week-in-rust.
 - Make *better* issues (more detailed) to help contributors getting started.
 - Implement more functionalities: There is still a ton of things to do, perhaps some people are waiting for some key missing features to be implemented?
 - Make more interesting demos that show what lyon can offer.
 - Move the repository from my github account into a dedicated github organization.
 - Reduce the complexity of the code if possible.

**Comment by Drakulix** [comment]
> File a more issues for newcomers to pick, advertise them in this-week-in-rust.

This. I would like to contribute sometime (although I have too many projects in general), but I have no idea, where to start, as the code base appears large and overwhelming.

More comments on the "easy" issues on how to approach it, would be very helpful. E.g. where to add the new functionality (files), how should the api look like, some implementation tipps for the underlying project.

> Implement more functionalities: There is still a ton of things to do, perhaps some people are waiting for some key missing features to be implemented?

I was mainly waiting for all the basic shapes to be fully implemented (especially rounded rectangle) as well as round line endings.
After that I wanted to prototype a game I wanted to build for a long time with this crate, that is the biggest reason I am watching this repository.

**Comment by nical** [comment]
Thanks a lot for your feedback! I'll start with adding details to the the issues labelled as easy and spend some time on the basic shapes, then.

Are there specific obstacles that make the code base appear overwhelming? Is it hard to understand the scope/goal of the project, the structure of the code and the repository, finding useful information in the documentation, or understanding the algorithms?

**Comment by Drakulix** [comment]
Mostly structure. It is nice, that the project is this modularized, but I have a hard time to figure out what parts of it can be used in combination and how they should fit together.

The overall purpose is very clear, but I don't feel like, I would know where to start without studying the examples in great detail at first (which was even more difficult, before you added the new simpler example).

This could most likely be resolved by some explanation and maybe some smaller examples in the giant meta-crate. That would be the place, I would expect a gentle introduction about how to start using this project.

**Comment by nivkner** [comment]
Hello @nical, 

I would like to contribute to #44 but as you probably already know, this issue is intimidatingly huge. Which is a shame because this kind of API fix is the perfect place to start contributing (as you can see from the the libz blitz). 

So I suggest you break down this issue In a manner similar to a crate evaluation, where each part of the API guideline that is relevant to lyon as an issue linked to in the meta-issue (no need to do a full evaluation right away, you can add issues as they are discovered by yourself and people commenting on the meta-issue). 

To not cause an overflow of issues, in the more complex issues like adding examples you can create a checklist separated based on modules, where one can claim a specific module, thus allowing multiple people to participate at once. 

To spare contributers the need to scan the entire issue you to see if anyone is working on a module, you might want to add an "in progress" next to a claimed module. You can even add alongside it the username of the claimant so they can be pinged for status updates.

So for example you might see something like this:

* svg 
    - ... 
* extra
    - ...
* tessellation
    -  [   ] basic shapes (in progress @nivkner)
    -  [   ] path fill
    -  [ x ] path stroke
    -  [   ] geometry_builder
* ... 

Even if you don't do any of that because that is admittedly a lot of work for an ad-hoc issue tracker, I would still like to suggest you make use of github's ability to assign users to issues, so that a new contributer could get a bird's eye view of which issues are available without reading every single one.

**Comment by nical** [comment]
Hey @nivkner, thanks for your feedback! Sounds good to me, I'll look into the rust API guidelines and split up issue #44 into more manageable units the way you suggested (at the moment I'm traveling so it might take a few days).
My github-jutsu is not as good as it should be so I may have missed something, but I am under the impression that I can only assign to issues people who are collaborators of the repository. Should I add people to the list of collaborators as soon as they express interest in contributing? I'll happily do it, though I initially felt it might be a bit overwhelming for a newcomer (looks like it sends them an email, etc.).

**Comment by nivkner** [comment]
Oh, I didn't know about the collaborator requirement. In that case: no, that would be too much ceremony for what might be a one-time contribution.

**Comment by nical** [comment]
Maybe an `assigned` label could get us most of the benefit for reasonable amount of effort.

**Comment by nivkner** [comment]
So, first of all, I'm glad you implemented my suggestion about breaking down the API guidelines issue. However, I'd also like to suggest that you rename the issues, for clarity's sake.

Instead of naming #88 "Rust API guidelines: C-MEANINGFUL-ERR", consider "return error type from functions instead of empty struct" or something similar. The name of the guideline can be used alongside the hyperlink to give people more information to work with, in addition to your description.

I think it is important for the issue name to be meaningful on its own, without relying on outside sources, and be actionable. So if someone is following "This Week in Rust" or just glances over the issue tracker, and sees this issue, they won't just ignore it because it isn't immediately obvious what it expects them to do.

**Comment by nical** [comment]
Good point, I'll look into fixing up the issue titles shortly.
