### ISSUE TITLE
Implement circle stroke tessellation.

### ISSUE THREAD

**Issue by nical** [nical/lyon#40]
A function `stroke_circle` should be added in [basic_shapes.rs](https://github.com/nical/lyon/blob/master/tessellation/src/basic_shapes.rs). The interface would be similar to `fill_circle`, using a `GeometryBuilder<StrokeVertex>` for the output.

The other tessellation routines in the same file provide a good set of examples for how to tessellate specific shapes with the `GeometryBuilder` API.

**Comment by nivkner** [comment]
I'll try out this one.

I already started on `stroke_border_radius`, and tried to do the divide and conquer style like in `fill_border_radius` but I found myself stuck since after I pick the first triangles, I am left with a full area that needs tessellation (the rest of the stroke) so recursion doesn't really fit.

So instead I'm thinking of dividing the whole border by a given number and producing an iterator of points so I can use `stroke_polyline`.

What do you think @nical?

**Comment by nical** [comment]
Hi @nivkner, thanks for looking into this! Using `stroke_polyline` sounds good. The subdivision should take the radius and a tolerance threshold into account, there's a function `circle_flattening_step` in the same file that gives you the length of a segment in function of these parameters (see how it is used in `fill_circle`). Let me know if there is anything I can do to help you get started!
