### ISSUE TITLE
NaNs break the fill tessellator in confusing ways

### ISSUE THREAD

**Issue by icefoxen** [nical/lyon#414]
A ggez user managed to create a shape that draws fine using `t::basic_shapes::stroke_polyline()` but which causes `t::basic_shapes::fill_polyline()` to panic.  In debug mode it complains of trying to subtract with overflow deep within `lyon`, in release mode `fill_polyline()` simply returns `Err` with `Internal(E01)`.  What I suspect is happening is that they're somehow creating a shape that `lyon` isn't able to tessellate, but I don't know where to go to investigate further.  

Partial debug backtrace:

```
thread 'main' panicked at 'attempt to subtract with overflow', /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/fixed.rs:245:33
stack backtrace:
...
   8: core::panicking::panic
             at libcore/panicking.rs:53
   9: <lyon_tessellation::fixed::Fp32<F> as core::ops::arith::Sub>::sub
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/fixed.rs:245
  10: <euclid::point::TypedPoint2D<T, U> as core::ops::arith::Sub>::sub
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/euclid-0.17.3/src/point.rs:176
  11: lyon_tessellation::path_fill::FillTessellator::tessellator_loop
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/path_fill.rs:431
  12: lyon_tessellation::path_fill::FillTessellator::tessellate_events
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/path_fill.rs:352
  13: lyon_tessellation::path_fill::FillTessellator::tessellate_path
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/path_fill.rs:327
  14: lyon_tessellation::basic_shapes::fill_polyline
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/basic_shapes.rs:820
  15: ggez::graphics::mesh::MeshBuilder::polygon
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.4/src/graphics/mesh.rs:205
  16: ggez::graphics::mesh::Mesh::new_polygon
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.4/src/graphics/mesh.rs:355
  17: ggez::graphics::polygon
```

Partial release backtrace:

```
thread 'main' panicked at 'Could not fill polygon?: Internal(E01)', libcore/result.rs:945:5
stack backtrace:
   8: core::result::unwrap_failed
   9: ggez::graphics::mesh::MeshBuilder::polygon
  10: ggez::graphics::mesh::Mesh::new_polygon
  11: ggez::graphics::polygon
```

Original bug report with working example program and full backtraces here: https://github.com/ggez/ggez/issues/470

Just failing in release mode with "this polygon is not able to be tessellated" is fine; ggez currently just unwraps the result lyon gives it and there's a comment right next to it saying `handling this error would be rather nice`, so that one's on me.  The subtract-with-overflow in debug mode is more mysterious though.  Let me know if there's anything I can do to help!

**Comment by nical** [comment]
Thanks for filing this. You are right, `InternalError(..)` means we ran into an error inside of the fill tessellator. In general it's some floating point precision error caused by self-intersections breaking the an ordering of edges and the algorithm gets into a weird state. However, from the linked ggez issue it seems that the problem in this case was caused by `NaN` values in the input path. Lyon currently doesn't handle NaN at all. I'm hesitant to add NaN checks in the tessellaotor because of the added cost for something that is usually easy to validate before passing to the tessellator, but it's something that I can revisit. I should document it, though.

I see that ggez uses the default [on_error](https://docs.rs/lyon_tessellation/0.11.0/lyon_tessellation/enum.OnError.html) setting in the `FillOptions` which is `Stop`. You can also set it to `Recover` which will make it so that when the algorithm detects an error, it does a best effort to give you something (doesn't always succeed) instead of stopping right away. It's something to consider if generating "something" is more important than getting an exact result. In the case of NaN I think that this wouldn't have succeeded in recovering anyway.

**Comment by icefoxen** [comment]
Thanks a lot for taking a look at that case.  Given the error is from user inputs and probably not recoverable, ggez is just going to detect the failure more gracefully; better to fail early than to give incorrect outputs.

**Comment by nical** [comment]
We do have [some debug NaN checks](https://github.com/nical/lyon/blob/master/path/src/default.rs#L165) when creating the `Path` object, but I'll add some more in the tessellator since `fill_polyline` skips building a `Path`.

**Comment by fschutt** [comment]
I ran into this with azul when I rendering bezier curves. I am currently constructing a polygon for each bezier curve and then stroking it, because I was not aware that lyon has regular functions to just tesselate lines (without constructing a polygon first).

```
[ERROR][azul::logging] An unexpected panic ocurred, the program has to exit.
Please report this error and attach the log file found in the directory of the executable.

The error ocurred in: libcore\result.rs at line 945 in thread main

Error information:
called `Result::unwrap()` on an `Err` value: Internal(E01)

Backtrace:

backtrace::backtrace::trace
<backtrace::capture::Backtrace as core::default::Default>::default
backtrace::capture::Backtrace::new
azul::logging::set_up_panic_hooks
std::panicking @ panicking.rs:482
std::panicking @ panicking.rs:390
std::panicking @ panicking.rs:325
core::panicking @ panicking.rs:77
core::result::unwrap_failed
azul::widgets::svg::SvgLayerType::tesselate
azul::widgets::svg::tesselate_layer_data
azul::widgets::svg::quick_lines
mapedit2::ui::render_node::render_connection_point
mapedit2::ui::render_node::render_connection_point
<std::sync::mpsc::shared::Packet<T>>::drop_port
<azul::display_list::DisplayList<'a, T>>::into_display_list_builder
<azul::app::App<T>>::run
<azul::app::App<T>>::run
mapedit2::svg_layers::text_to_displaced_text
std::io::Write::write_all
std::panicking::try @ panicking.rs:310
panic_unwind @ lib.rs:105
std::rt @ rt.rs:58
 @ exe_common.inl:283
```

In the screenshot below, I'm drawing the paths between node connections via lyon and I can reliably reproduce this bug with a certain constellation of node positions, so I could dump the node positions (and therefore the bezier curve points which I use to draw the line) and create a test case for lyon.

![image](https://user-images.githubusercontent.com/12084016/48493529-47773580-e82c-11e8-9b3b-13f9368d2df6.png)

The bug is probably because I am creating a fill tesselator here: https://github.com/maps4print/azul/blob/8586f0f84f81dd25368d98954d8a08e1ddb08dd1/src/widgets/svg.rs#L1425-L1426 - regardless of whether the polygon is filled or not (in the case of bezier curves, the polygon obviously isn't filled). However, this bug shouldn't happen regardless (also it happens in release mode, so it's not debug_assert! - maybe a different bug?)

**Comment by nical** [comment]
> In the screenshot below, I'm drawing the paths between node connections via lyon and I can reliably reproduce this bug with a certain constellation of node positions, so I could dump the node positions (and therefore the bezier curve points which I use to draw the line) and create a test case for lyon.

A test case would be very helpful!
