### ISSUE TITLE
Link tessellated vertices to the path curves

### ISSUE THREAD

**Issue by kvark** [nical/lyon#471]
When looking at the tessellator results, is there a way to associate each vertex (or triangle) with a subset of path curves that define its placement?

**Comment by nical** [comment]
Your motivation looks similar to #439.
At the moment there is no good way to precisely associate arbitrary data with vertices. To make it worse the vertices the tessellator produces are almost but not quite the same as the input vertices because the tessellator internally converts them into a fixed point representation.

This feature is very high in my list but it's a little tricky to do because the tessellator can merge coincident vertices or insert new vertices at intersections. I haven't given up on it but I can't promise it in the short term.

**Comment by kvark** [comment]
I'm not asking for arbitrary data. I'm asking for the curve data that is the tessellator input. I.e. if a tessellator produces a triangle, all points inside the triangle are closer to either curve A or curve B among all the curves on the path, I want the vertex data to have access to this list of [A, B] in some form.

**Comment by nical** [comment]
So if I understand correctly what you are interested in is which edges of the triangles are at the boundary of the path?

If so I need to think about it. I might be able to track that information in the tessellator and give you some thing in `GeometryBuilder::add_triangle` like maybe a array of 3 `bool`s that tell you for each edge of the triangle if it is at the boundary of the path.

**Comment by nical** [comment]
The new tessellator that just made into the master branch is able to link vertices to path endpoints (or were in-between endpoints for vertices intoduced at intersections or during curve flattening). It may not exactly not exactly be what you are after but it's close.
