### ISSUE TITLE
Incorrect path tesselation

### ISSUE THREAD

**Issue by HalfVoxel** [nical/lyon#537]
The snippet below produces an incorrect tesselation as far as I can tell.

```rust
let mut test_geometry: VertexBuffers<GpuVertex, u16> = VertexBuffers::new();
let mut builder = Path::builder();
builder.arc(Point::new(50.0 + 5.0, 50.0 + 0.0), vector(10.0, 5.0), Angle::degrees(300.0), Angle::degrees(1950 as f32));
builder.line_to(point(0.0,0.0));

let p = builder.build();
StrokeTessellator::new().tessellate_path(
    &p,
    &StrokeOptions::tolerance(0.1 / 46.91137).with_line_width(1.0),
    &mut BuffersBuilder::new(&mut test_geometry, WithId(0 as i32))
).unwrap();
```

Below is a screenshot of the error. The path is rendered in transparent pink with z testing mode Equal or Greater, which means overlapping geometry shows up. You can see a missing triangle between the curve and the straight part. This part corresponds to the join between the arc and the line_to command. The grey and blue part in the screenshot can be ignored.
It can be noted that if this issue shows up depends on the path tolerance. For most tolerance values it does not show up.

![image](https://user-images.githubusercontent.com/1144597/74092136-5c3e8980-4ac0-11ea-9aa8-cfa34a32f474.png)

The full source code for a reproducible example can be found at https://pastebin.com/gFa5kiYf (the relevant part starts at line 511).
It is based on the wgpu example, so the source code of that example can be replaced with this and then built using cargo.

**Comment by nical** [comment]
Thanks for the test case, I'll look into that shortly.

Off hands it looks like an issue with how the stroke tessellator's implementation only looks at two consecutive edges (after flattening curves into line segments) to figure the join. The next edge doesn't really know about the join so if it is smaller than the stroke width it can lead to self-overlap. Unfortunately this is kind of hard to fix in the stroke tessellator due to the naïve nature of the algorithm. The only reliable way I know to properly tessellate strokes is to generate a path that represents the fill of the stroke and put it though the fill tessellator. Alas it's  much more expensive to do and I haven't gotten around to implementing the stroke to fill algorithm yet (although I believe it's not a very complicated one).

That said the deffect of the stroke algorithm I mentioned shouldn't produce cracks like there is on this screenshot, so there's something else going on.

**Comment by HalfVoxel** [comment]
Great!

I'm not worried about the overlapping geometry. That is expected and as you say, pretty hard to avoid.
I only included it as I thought it might make it easier for you to debug. Overlapping geometry can easily be worked around using z-test=Greater in any case.

It's the crack between the curves that is important.
