### ISSUE TITLE
Rework the builder traits

### ISSUE THREAD

**Issue by nical** [nical/lyon#541]
The traits in `path/src/builder.rs` need a bit of polish.
 - most of it is not used very much,
 - there is some code that could be de-duplicated,
 - the arc flattening should move_to when the current sub-path doesn't have a current point,
 - it's not clear to me whether we need all of the traits. Perhaps `FlatPathBuilder` isn't that useful and we could get away with only the regular builder and an SVG extension trait.

**Comment by HalfVoxel** [comment]
That's great! I was thinking the other day that there seemed to be a lot of duplicated code there.
FlatBuilder seems like it should be equivalent to flatting a builder's curve every time one is added.
Then again, is this even such a big win performance/memory wise? Sure it saves some allocations, but the number of curves in a path is usually pretty low compared to the flattened representation right? 
To me it seems better just have a flattening step after the whole builder has been finalized. Unless it turns out there is actually a significant different in performance.

**Comment by nical** [comment]
We could keep the flattening adapter without having a specific `FlatPathBuilder` trait expressing builders that can only do line segments is what I meant. We could also get rid of the adapter altogether, or keep it but reorganize the glue code so that it's reused in other places.

How big of a win one gets from the flattening adapter depends on what they do and what the workload is. If you are going to keep a flattened version of a path, then building it flattened right away is a lot less work for sure. But it's kind of theoretical if nobody uses it (I don't know whether that is the case). Perhaps there isn't a compelling use case for building a flattened path and reusing it multiple times.

**Comment by nical** [comment]
The builder API was revamped in the master branch (not published yet)
