### ISSUE TITLE
Behaviour change related to arcs in lyon_geom between 0.15.0 and 0.15.2

### ISSUE THREAD

**Issue by jdm** [nical/lyon#587]
When I update Servo to use 0.15.2 in https://github.com/servo/servo/blob/master/components/canvas/Cargo.toml#L30 instead of 0.15.0, we get a new test failure in the WPT canvas tests:
```
/html/canvas/element/path-objects/2d.path.arc.shape.1.html
  FAIL arc() from 0 to pi does not draw anything in the wrong half - assert_equals: Red channel of the pixel at (20, 48) expected 0 but got 63
_assertPixel@http://web-platform.test:8000/html/canvas/resources/canvas-tests.js:38:18
@http://web-platform.test:8000/html/canvas/element/path-objects/2d.path.arc.shape.1.html:33:13
Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
_addTest/</<@http://web-platform.test:8000/html/canvas/resources/canvas-tests.js:66:15
Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
_addTest/<@http://web-platform.test:8000/html/canvas/resources/canvas-tests.js:63:11
```
I'll try and figure out what the test is doing and how lyon_geom is used in it.

**Comment by jdm** [comment]
cc @atouchet

**Comment by jdm** [comment]
Test contents:
```js
ctx.fillStyle = '#0f0';
ctx.fillRect(0, 0, 100, 50);
ctx.lineWidth = 50;
ctx.strokeStyle = '#f00';
ctx.beginPath();
ctx.arc(50, 50, 50, 0, Math.PI, false);
ctx.stroke();
```
We use Arc from lyon_geom for the arc API in [this code](https://github.com/servo/servo/blob/5f6a05e71575f1d18650334fef1cd0d1985db839/components/canvas/raqote_backend.rs#L701-L757).

**Comment by jdm** [comment]
This behaviour change was introduced in 21fe9cb1c6d8e939050712a93e965b06aab6fb5e.

**Comment by jdm** [comment]
Test output before adf530bd6b9d67d719f88cfc41abc721742b8998:
<img width="389" alt="Screen Shot 2020-06-04 at 3 53 51 PM" src="https://user-images.githubusercontent.com/27658/83804227-cab0e400-a67b-11ea-9d68-daf4a3b211b5.png">
Test output after adf530bd6b9d67d719f88cfc41abc721742b8998:
<img width="378" alt="Screen Shot 2020-06-04 at 4 04 00 PM" src="https://user-images.githubusercontent.com/27658/83804993-0ac49680-a67d-11ea-9c55-90403a57d4d3.png">

**Comment by nical** [comment]
That commit changed the algorithm used to approximate curves with line segments. From the look of the test outputs, the issue is that the red arc should not show at all. I suspect the reason it is showing is because the path is first flattened into line segments, and  in doing so we lose some information about the tangent of the curve at the endpoints. This issue is inherent to flattening and while the artifact may vary depending on the flattening approximation (as the detected change shows), the issue/solution lied in the code that uses the flattening algorith. It should record the tangent before flattening so that the rendering of the arc is more precise at the endpoint.

raqote has an issue on file about this: https://github.com/jrmuizel/raqote/issues/96
