### ISSUE TITLE
Extrude 2d tessellation into 3d prism?

### ISSUE THREAD

**Issue by twitchyliquid64** [nical/lyon#626]
Hi!

Im trying to extrude a 2d polygon with cutouts into a 3d prism. So far, ive tessellated using lyon, and am trying to work out how to duplicate the vertex/indices into 3d space.

Is this a thing lyon is interested in, or something that lyon has opinions about the implementation / design of?

I'm trying to implement this myself, but keen to share or collaborate if theres interest.

**Comment by nical** [comment]
Hi,

Lyon operates in 2D but it should already give you the tools you need for this (mostly).

- Assign an endpoint ID to each point of your original path. Either this ID is the index of the vertex or some way to look up the index.
- During tessellation you can get this ID in `FillGeometryBuilder::add_fill_vertex` using `FillVertex::as_endpoint_id` or iterating over `FillVertex::souces`.
- Since you know during tessellation the ID of the original point you can generate the sides of the extrusion by generating triangles that connect the new vertices the tessellator is generating with the ones from the original path.

You can make it work with bezier curves but it's probably easier if you flatten the path before tessellating so that each point in the path has an endpoint ID. 

Of course your original path might not be in the xy plane. You have to project it on the xy plane first, do the tessellation, then apply the inverse transformation to project back in 3d space.

The main missing part is that this does not tell you the side of the normal vector for your sides. If you are working with a simple enough shape you can maybe guess either by comparing vertex positions with the center of the shape or perhaps you have some knowledge about the shape, for example the path could have been built so that the outside is always on the left of each edge. I might find a way to add a way to compute normals in the tessellator but it's a niche use case so I want to do it without causing overhead for the common case where normals aren't needed.

There is also a complication when your path has self intersections. In this situation the tessellator has to introduce new vertices at the intersections. Since there is no endpoint in the original path corresponding to these, `as_endpoint_id` will return `None`. You can still iterate over  `FillVertex::as_endpoint_id` and it will give you enough information to know which edges of the original path produced the intersection. From there you can patch up the original path to introduce the intersection point, it's a bit fiddly but you have enough information to make it work. In general though, 3d models tend to avoid self intersections because it causes a lot of annoyance with many other algorithms so you can go a long way pretending there is no self-intersections in the loop you are extruding, or pre-process it to resolve the self-intersection before tessellating.

**Comment by twitchyliquid64** [comment]
Thanks @nical!

I had a lot of difficulty getting this to work as a `FillGeometryBuilder` so eventually I explored working exclusively on the tessellated output of `lyon`.

Top and bottom faces are easy (just copy pasta twice the verts/inds from lyon, and add a third dimension for Z with `-height/2` or `height/2` for the bottom and top faces respectively). Side faces were more challenging.

Given that only the 2d boundary 'lines' (ie: a pair of vertices) could be edges that need to be 'stitched' with their copy-pasta'd counterpart, i focused on finding those and manually building the two triangles needed for each face of the side. Boundary lines are only seen once (ie: that vertice pair is not part of multiple triangles), so I figured if you count occurrences you can find the boundary lines that need stitching between the top and bottom:

```rust
    // Iterate through the edges represented by the indices, building a map
    // of the indice indexes which use it.
    let mut lines: HashMap<(u16, u16), Vec<(usize, bool)>> =
        HashMap::with_capacity(buffer.indices.len());
    // For the three corners of each triangle ...
    for (i, in3) in buffer.indices.chunks_exact(3).enumerate() {
        // Loop each edge (line) of the triangle ...
        for (i, verts) in &[
            (i * 3 + 0, &[in3[0], in3[1]]),
            (i * 3 + 1, &[in3[1], in3[2]]),
            (i * 3 + 2, &[in3[2], in3[0]]),
        ] {
            // We make sure a forward or reverse edge
            // maps to the same key (2->1 is the same as 1->2).
            let key = (verts[0].min(verts[1]), verts[1].max(verts[0]));

            // ... And track how many times we see an edge between those
            // two points, by inserting it into the hash map.
            match lines.get_mut(&key) {
                Some(v) => v.push((*i, verts[0] < verts[1])),
                None => {
                    lines.insert(key, vec![(*i, verts[0] < verts[1])]);
                }
            }
        }
    }

    // Edges which are on the boundary of the polygon are those which are only
    // part of a single triangle.
    let mut boundary_lines: Vec<_> = lines
        .into_iter()
        .filter(|(_k, v)| v.len() == 1)
        .map(|(k, v)| (k, v[0])) // (v1, v2), (idx, ordered)
        .collect();
    // Sort them into the order in which they appeared in the original index buffer.
    boundary_lines.sort_by(|a, b| a.1 .0.cmp(&b.1 .0));
```

From there, it looks like looping through that in natural order and yeeting out triangles counter-clockwise works?

```rust
   let c = 2d_vertex_buffer.len(); // offset from c are the top-face verts
   for ((v_low, v_high), (_, original_order)) in boundary_lines {
        if !original_order {
            indices.push(v_low);
            indices.push(v_high);
            indices.push(v_low + c);
            indices.push(v_high);
            indices.push(v_high + c);
            indices.push(v_low + c);
        } else {
            indices.push(v_high);
            indices.push(v_low);
            indices.push(v_high + c);
            indices.push(v_low);
            indices.push(v_low + c);
            indices.push(v_high + c);
        }
    }
```

As for the normal, papa Google said thats just the vector cross product, so calculating that for that triangle seems to work. I've been careful to try and keep the winding order that lyon hands out, so hoping theres no edge cases im missing.

![image](https://user-images.githubusercontent.com/6328589/104794296-8a5e2c00-575b-11eb-9833-2e8d5f785dc2.png)

![image](https://user-images.githubusercontent.com/6328589/104794320-abbf1800-575b-11eb-961b-c4bd1ad2eb98.png)

I appreciate this is a rather dodgy approach, but happy to put the code somewhere if you think its acceptable.

**Comment by nical** [comment]
You know, if it solves your problem, then it's acceptable (whatever it is). You do a sort of heavy lifting to figure out the boundary edges, which I think you can avoid some of the advanced features I described earlier. But it really doesn't matter as long as your code does what you need it to already.

**Comment by nical** [comment]
Looks like your question is resolved, good luck with your tessellation in 3d endeavours!
