### ISSUE TITLE
normals during tessellation

### ISSUE THREAD

**Issue by caperaven** [nical/lyon#690]
Is there a way to get lyon to include the normal data for the generated faces?

**Comment by nical** [comment]
I suppose you mean vertex normals in 2D rather than face normals since the produced tessellation is flat.I have a somewhat experimental [branch](https://github.com/nical/lyon/tree/normals) that tries to provide that, however it can't provide normals to vertices that are inserted where the shape self-intersects.

If you want to experiment with that branch, it adds a `fn compute_normal(&self) -> Option<Vector>` method to `FillVertex` which returns a `Some(Vector)` in most cases but `None` for self intersections and more generally vertices where more than two edges meet.

Let me know whether it properly addresses you use case.
