### ISSUE TITLE
Maximum Advancement on Stroke Tessellator

### ISSUE THREAD

**Issue by anlumo** [nical/lyon#700]
The StrokeTessellator supplies an advancement property that tells the StrokeGeometryBuilder how far into the stroke the vertex is. This is great, however you usually want to divide by the full length, so you get a normalized value between 0.0 and 1.0. For this, the application needs to know the total length of the stroke, but there's no way to get that value (or at least I haven't found any). I've resorted to going through the whole vertex array and just looking for the maximum value, which is easy enough but O(n). It should be trivial to reveal this value to the application, since the tessellator does have this information.

**Comment by nical** [comment]
The stroke tessellator doesn't actually have this info, it accumulates the length during the tessellation. You could compute the approximate length using https://docs.rs/lyon_algorithms/0.17.5/lyon_algorithms/length/fn.approximate_length.html before or after tessellating the path but that's also O(n).
If that's too expensive the fastest approach is probably to compute the length manually while building the path using similar code as `approximate_length`, (for example creating your own path builder that wraps the original one) so that you at least don't need an extra traversal.
