### ISSUE TITLE
Cannot Create a Flattened IterWithAttributes

### ISSUE THREAD

**Issue by anlumo** [nical/lyon#701]
`PathIterator` implements a `flattened` function that returns an iterator over the flattened curve.

However, this trait is only implemented for the trait `Iterator<Item = PathEvent<Point, Point>>`. `IterWithAttributes` implements `Iterator<Item = PathEvent<(Point, &[f32]), Point>>`, so there's no way to flatten a path with attributes.

I think that this also needs `impl<Iter> Iterator for Flattened<Iter> where Iter: Iterator<Item = PathEvent<(Point, &[f32]), Point>>`, which doesn't seem to exist right now.

**Comment by nical** [comment]
Yeah, I haven't gotten to implementing that yet. It would be a useful addition, I'll look into it whenever I have some time.

**Comment by anlumo** [comment]
This might be an API stability thing, but why do you even need a completely separate tree of types for paths with attributes vs. paths without them? Shouldn't a path with 0 attributes be equivalent to one without attributes?

**Comment by nical** [comment]
I had a look and and it turns out that this feature is quite hard to express in rust using the iterator trait.

The problem is that while iterating, the iterator needs to compute and write the interpolated attributes somewhere. It could be either a buffer owned by the iterator, or some externally provided buffer that the iterator owns a mutable reference to. the `Item` of the iterator would need to contain a `&'Self [f32]` where `'Self` represents the lifetime of the iterator's `&mut self` reference, but that can't be expressed in current rust.

A simplified example here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a7e3298ae91f1bc411e803748693bb4a

Externalizing the buffer and having the iterator hold a &mut reference to it does not help. It lets us name the lifetime of the buffer but we are still unable to express that the lifetime of the item is a subset of the iterator's self (since we'll need to overwrite the data in the next loop iteration). See https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=230d1574c8ca50f096da8074c402def3

When I asked around, "Generic associated types" came up, which is on one hand encouraging, but on the other hand probably not for the near future.

I don't want to expose an API that allocates a new buffer at each iteration, so in the near future the only Okay-ish thing to do is to have a callback based API that would look like:

```rust
path.iter_with_attributes().for_each_flattened(tolerance, |event| {
    // ...
});
```

It's a bit unidiomatic but at least it can be expressed in safe rust. Would that be helpful to you?

**Comment by anlumo** [comment]
I just played around a bit in the playground, I also can't find a way to make it work.

Your proposed API would work for my use case, although a `.map_flattened` would also be nice.

Thank you for looking into this!

**Comment by anlumo** [comment]
Question about the API: Since `for_each_flattened` consumes the path, why doesn't it pass in `Event` rather than `&Event` in the closure? Looking at the code, passing ownership would make more sense and it'd make the borrow checker happier.

**Comment by nical** [comment]
Could you go into the specifics of the borrow checker issues you are facing?

As a rule of thumb, when I have the choice I tend to decide what gets passed by value or by reference depending on its size with a threshold around 128 bytes, especially for public facing APIs. The reason is that unless function calls are inlined, large structs have to be copied on the stack to be passed to functions. At first it sounds like it's not a problem because computers are fast, but in practice I spent a fair amount of time in another project getting substantial performance improvements by optimizing away this type of moves.
The reason I say "especially for public facing APIs" is that rustc is very shy about inlining across crates (as in, if your function is not makred inline or is not generic, you can be certain that is not inlined when called from another crate). Perhaps this specific instance would get properly inlined and optimized if events were passed by value, but verifying that takes time (can't just look at the codegen in the playground). Ultimately it's just a lot easier and less time consuming to follow a simple rule of thumb (with margin to break it whenever needed), and it makes for more consistent APIs.

**Comment by anlumo** [comment]
`Event` is `Copy`, so that could easily be optimized out, although I haven't done any assembly output analysis of the Rust compiler.

> Could you go into the specifics of the borrow checker issues you are facing?

It turns out that the problems I had was the `&[f32]` reference inside `Event`, making it have a non-static lifetime. For the longest time I just looked at the docs while trying to figure out why it wasn't `'static`, but since this is a generic parameter, of course this doesn't show up there.

Now my code just looks like this:

```rust
        let mut output: Vec<(Point, f32)> = Vec::new();
        input.for_each_flattened(1.0, &mut |event| {
            match event {
                Event::Begin { at } => {
                    output.clear();
                    output.push((at.0, at.1[0]));
                }
                Event::End { last, first, close } => {
                    // TODO: handle close flag!
                }
                Event::Line { from, to } => output.push((to.0, to.1[0])),
                _ => unreachable!(),
            }
        });
```

**Comment by nical** [comment]
Having to copy large-ish structs that are passed by value is independent from whether the type is `Copy` or not. That's an ABI/calling convention thing and the compiler can only optimize it if it inlines the function call.
You can try to decide what to pass by values by inspecting assembly of various consumers of a particular function (in various compiler versions) if you are adventurous. As far as I am concerned, the simple rule of thumb has served me well, I'm happy to stick to it.

The `&[f32]` unfortunately can't be static. It points to a temporary buffer in which the interpolated attribute values are computed between each iteration.
