### ISSUE TITLE
FillTessellator face winding

### ISSUE THREAD

**Issue by caperaven** [nical/lyon#717]
Using the results of FillTessellator in WebGL (threejs) only works for me when I use double sided materials.
I think this might be because the face winding might be in the wrong direction for WebGL.
Not 100% sure though.
Is there a way where I can define the face indices to be clock vs counter clock wize when generating the face data in a FillTessellator?

**Comment by nical** [comment]
The generated triangle winding is always such that `(b - a).cross(c - b) < 0`. In the short term, the simplest way to invert the winding is:
 - If you are implementing your own `GeometryBuilder`, then just swap two of the vertices in `add_triangle`.
 - If you are using the provided `BuffersBuilder` as `GeometryBuilder` for convenience, then you have to implement your own `GeometryBuilder` instead. It's rather simple, you can look at `BuffersBuilder`'s source code and make an even simpler one since you won't need as many generics.

I'll probably add an option in `BuffersBuilder` to invert the winding in version `0.18` which is coming in the next few weeks.
The alternative would be to add a parameter to the tessellators for that but I'm not fond of all of the extra branchiness in there for something that is typically statically known.

**Comment by caperaven** [comment]
The current code that I am using is this.

```
pub fn create_fill(path: &Path) -> PolyBuffer {
    let mut buffer: PolyBuffer = VertexBuffers::new();
    {
        let mut vertex_builder = simple_builder(&mut buffer);
        let mut tessellator = FillTessellator::new();

        tessellator
            .tessellate_path(path, &FillOptions::default(), &mut vertex_builder)
            .ok();
    }
    return buffer;
}`

It's not a critical matter for us just yet and we can wait for an update, if it is planned for the future.

**Comment by nical** [comment]
OK you are using `simple_builder` which retruns a `SimpleBuffersBuilder` which is sugar for a `BuffersBuilder` that just stores a `Point` per vertex.

If you end up later copying the points to store them in some other format later, my recommendation is to create your own builder so you can skip that extra copy (and flip the winding in the process). In any case I'll keep you updated here with whatever happens for 0.18.

**Comment by nical** [comment]
Fixed in the latest version on crates.io. See `BuffersBuilder::with_inverted_winding`.

**Comment by andrewvarga** [comment]
I found the same issue using `wgpu` with a standard `Ccw` frontface render setting.
I could fix my issue by using `BuffersBuilder`'s `with_inverted_winding()`. Is that the standard way to solve this?
It seems a bit unusual at first that the output indices are `Cw` instead of `Ccw` regardless of the path's orientation.

**Comment by nical** [comment]
There isn't a standard default triangle winding,IIRC D3D and GL have different defaults. `with_inverted_winding` is one way to flip the winding on lyon's side or you can take the winding you want into account if you implement the Fill/StrokGeometryBuilder traits or even set whichever winding you want on the GPU API side at your convenience. 

Had WebGPU been a thing many years ago I'd have looked into aligning with its defaults but at this point, changing the default winding in lyon would silently break too many people's code so it's pretty much set in stone now.

**Comment by andrewvarga** [comment]
Makes sense, thank you!
I meant more like standard for my use case which is WebGPU / WebGL so the OpenGL flavour.
`with_inverted_winding` works pretty well, I tried to implement my own FillGeometryBuilder before finding that but I was having a bit of trouble with it, partly due to my rust inexperience. Is there any performance difference between that and using `with_inverted_winding`?
Does the doc have a code snippet about implementing FillGeometryBuilder in a way that it overrides `add_triangle`?

**Comment by nical** [comment]
There shouldn't be a measurable difference unless you need to build something other than a pair of vectors for vertices and indices (BuffersBuilder is a straightforward implementatio of Fill/StrokeGeometryBuilder which does that).

> Does the doc have a code snippet about implementing FillGeometryBuilder in a way that it overrides add_triangle?

The implementation of `InvertWinding<Builder>` whihc is what `with_inverted_winding` gives you is a straightforward as it gets:

https://github.com/nical/lyon/blob/2570b94fd39f0309e7338da9f06a2573b521a949/crates/tessellation/src/geometry_builder.rs#L353

The tessellators always give you triangles in a consistent winding order so if it gives you a triangle with indices `a b c` and you would like to invert the winding order, you can simply flip two of the indices, for example `b a c` or ` a c b`.
