### ISSUE TITLE
Is there a way to do "incremental" tessellation instead of "full" tessellation every time?

### ISSUE THREAD

**Issue by CoorFun** [nical/lyon#746]

**Comment by CoorFun** [comment]
To be more precise, I have a Vec<Path> as the input for tessellation, and the next turn only some certain indexed paths are changed. I would like to find a way to only "patch" those changes to the previous tessellation output instead of running the full tessellation for all of them.

**Comment by nical** [comment]
Hi, while it's not possible to incrementally run the tessellation within a single path, it's up to you to handle updating a single path withing a group of paths (since that's happening outside of the tessellation algorithm).

The problem is somewhat similar to writing a memory allocator. For vertices you don't have to store them contiguously in a single block so there's a lot of flexibility in how you would place them in the VBO, for indices ordering may or may not be important depending on what you want to do with it. You could simplify the problem a bit by sub-allocating fixed size chunks into the vertex buffer. For indices you can do a lot fancy allocation/packing tricks or just have a copy of each path's indices somwhere and re-pack all of the indices each time something changes (or all of the indices starting at the first change) to avoid gaps.

You might be currently using something like `BuffersBuilder` or `simple_builder` to write the output of the tessellation. Note that these are there for convenience but you are encouraged to write your own implementation of the `GeometryBuilder` and `FillGeometryBuilder` traits if what you need is anything more elaborate than "push at the end of a pair of vectors".
