### ISSUE TITLE
Exposing `Verb` publicly

### ISSUE THREAD

**Issue by murtyjones** [nical/lyon#755]
Is there any reason why [`Verb`](https://github.com/murtyjones/lyon-pdf/blob/e063943767e94942c030ce0a7c4d3a47ff87fb25/crates/path/src/path.rs#L25) should not be exposed publicly?

My thinking is that for building on top of Lyon, [this pattern](https://github.com/murtyjones/lyon-pdf/blob/e063943767e94942c030ce0a7c4d3a47ff87fb25/crates/path/src/path.rs#L417-L421) is useful to copy and would require `Verb` to be public

**Comment by nical** [comment]
The link to the useful pattern doesn't work, are you referring to how paths are encoded as a buffer of coordinates and a buffer of verbs?

`Verb` is an internal detail of the path data structure and users of the data structure don't interact with it directly. I keep it private in part for API stability. It's pub(crate) out of laziness because `PathBuffer` needed something similar, but in principle `PathBuffer` should just have its own private Verb enum, and potential new data structures with similar needs can also duplicate it and add their own twists if need be, it's a pretty trivial thing to duplicate.

**Comment by murtyjones** [comment]
Whoops, yeah I was referring to this structure:

```
points: Vec<Point>
verbs: Vec<Verb>
```

To your point about duplicating `Verb`, I'd like to implement a data structure that implements the `Build` trait and can be converted to a `Path` for consumption by the tesselators:

```
impl Build for Pdf {
    type PathType = Path;

    fn build(mut self) -> Path {
        Path {
            points: self.points.into_boxed_slice(),
            verbs: self.verbs.into_boxed_slice(),
            num_attributes: 0,
        }
    }
}
```

But this obviously can't be done without access to `Verb`. 

I gather from this issue and our e-mail thread that maybe I should be skipping these data structures altogether for my use-case and going straight to constructing something that implements `IntoIterator<Item = PathEvent>`.

**Comment by nical** [comment]
If I understand correctly you need not only `Verb` but also all of the members of `Path` to be public.

> I gather from this issue and our e-mail thread that maybe I should be skipping these data structures altogether for my use-case and going straight to constructing something that implements IntoIterator<Item = PathEvent>.

Yep that's what I would recommend.
