### ISSUE TITLE
Configure stroke position

### ISSUE THREAD

**Issue by junglie85** [nical/lyon#839]
Is it possible to configure the stroke position with respect to the edge of a shape? Setting `StrokeOptions::with_line_width(50.0)` for example does not seem to change the width of my line. Using the code from the wgpu example where the width is set in the shader, with a value of 50.0, the stroke extends 25.0 in and 25.0 out of the edge of the shape.

e.g. if I have a 200x200 square and a stroke width of 50, it becomes a 225x225 square but I want it to stay as a 200x200 square.

I could adjust the size of the fill shape accordingly, but it'd be good to know if there's a way to configure this with Lyon?

Thanks :-D

**Comment by nical** [comment]
The wgpu example does something a bit special with line width, instead of using `vertex.position()` in the vertex constructor, it uses `vertex.position_on_path()` and the vertex normal to position the vertex in the shader (so that the line width can be modified after tessellation). https://github.com/nical/lyon/blob/master/examples/wgpu/src/main.rs#L738
That's why changing the line width in the stroke options in the example does not change the rendered line width.

If you need the the vertices to be offset differently depending on which side they are, you can use `vertex.side()` in your logic in a `StrokeVertexConstructor` or `StrokeGeometryBuilder`.

**Comment by junglie85** [comment]
Ah, okay. That’s helpful to understand, thank you for explaining. I’ll take a look at those methods and see how I can adapt the code accordingly. Thanks.

**Comment by junglie85** [comment]
That helped a lot, thank you.
