### ISSUE TITLE
wgpu_svg example fails to render lamborghini svg

### ISSUE THREAD

**Issue by akhildevelops** [nical/lyon#855]
https://github.com/nical/lyon/tree/master/examples/wgpu_svg example fails to render lamborgini svg file.

Source: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/gallardo.svg

![gallardo](https://user-images.githubusercontent.com/6951100/221568700-041ef6a2-a544-4a91-99e1-49205adb1eff.svg)

**Comment by akhildevelops** [comment]
Got below rendering

![image](https://user-images.githubusercontent.com/6951100/221569231-43938e25-7415-4c7f-bd9e-ca2c6382b1be.png)

**Comment by nical** [comment]
Yeah that's to be expected, somewhat. The svg rendering example is very very simple, it only handles filled paths with solid colors and basic transforms. Everything else is ignored, including gradients, clips, etc.

Considering that, the lamboghini actually renders surprisingly well (the shapes look correct modulo a few missing transformations which is mostly what the example demonstrates).

I might retire the SVG example since it is a bit misleading.
