### ISSUE TITLE
FillTesselator produces empty indices

### ISSUE THREAD

**Issue by Bathtor** [nical/lyon#911]
Hi, I'm observing the following behaviour and I'd like some feedback if that is a bug or expected behaviour that I simply don't understand because I'm new to graphics:

I observe that sometimes the `FillTesselator` produces an empty `indices` vector in the `VertexBuffers` object when tesselating a `Path`, even though `vertices` is not empty.

Here is an example from my debug logging:
```
Tesselated object with no indices: geometry=[Vector3 [-572.83246, 138.95511, 0.0], Vector3 [-572.83234, 138.94075, 0.0], Vector3 [-571.5453, 138.51, 0.0]], path=" M -572.83234 138.94075 L -572.83246 138.95511 L -571.5453 138.51 Z"
```

I'm using the following code to produce this (where `path: Path` is what is printed above):
```rust
let mut geometry: VertexBuffers<Vec3, u32> = VertexBuffers::new();
    let mut tessellator = FillTessellator::new();
    {
        // Compute the tessellation.
        let res = tessellator.tessellate_path(
            &path,
            &FillOptions::default()
                .with_fill_rule(FillRule::EvenOdd)
                .with_intersections(true)
                .with_sweep_orientation(Orientation::Horizontal),
            &mut BuffersBuilder::new(&mut geometry, |vertex: FillVertex| {
                vertex.position().as_vec().extend(0.0)
            }),
        );
        match res {
            Ok(geom) => geom,
            Err(TessellationError::GeometryBuilder(GeometryBuilderError::TooManyVertices)) => {
                panic!("Geometry had too many vertices: {}", path.iter().count());
            }
            Err(e) => panic!("Error during tesselation: {e}"),
        }
    }

    // Sometimes the tesselator just forgets to assign indices to trivial shapes.
    if geometry.indices.is_empty() {
        log::warn!(
            "Tesselated object with no indices: geometry={:?}, path={:?}",
            geometry.vertices,
            path,
        );
    }
```

I can go and manually fill in the indices and it will render fine, e.g.:
```rust
if geometry.vertices.len() == 3 {
      geometry.indices = vec![0, 1, 2];
} else if geometry.vertices.len() == 4 {
   geometry.indices = vec![0, 1, 2, 2, 3, 0];
}
```

I've only observed this in my dataset for (closed) polygons with a maximum of 5 vertices. And they tend to be long and narrow.

I also tried the `StrokeTesselator` and it produces the expected output for every single instance I observed.

# Versions

- lyon: 1.0.1
- Rust: `rustc 1.79.0-nightly (9d79cd5f7 2024-04-05)` (this is produced by the `wasm32-unknown-unknown` target)

**Comment by nical** [comment]
There is no indices produces with this input because within the provided tolerance threshold, the shape has no area (it's too close to being a slim line segment. If you lower the tolerance to, says, `0.01`, you should see a slim triangle instead of nothing for this particular input.
The tessellator does produces vertices in all cases because they are added before the algorithm finds out whether there is area to fill between them.

**Comment by Bathtor** [comment]
Aha! That makes sense. I was somehow under the impression that the tolerance is only used for approximating bezier curves, so I didn't even play with it. Thank you for the explanation.

Reducing the tolerance indeed fixed like 99% of my shapes with this issue. I have a few left that are so crazy narrow that I can't seem to find a tolerance value small enough. But I think I can live with just replacing them with their bounding boxes so they are visible at all.

On more question, if you don't mind: Can you give me an idea what the impact of reducing this tolerance to a very small value is? I assume it affects performance? Could it also blow up some shapes? (Assume no curves involved.)

**Comment by nical** [comment]
The biggest impact of the tolerance parameter is in the curve flattening as you guessed. In the tessellation algorithm (after curves are flattened) it only impacts whether two points are close enough to be merged into a single one, so for most paths it doesn't change much unless the shape is a big soup of edges that intersect one another a lot around the same spot.
That said, if the curve flattening produces a lot more edges, it does make tessellation measurably slower so that's tytpically where you'll see the biggest impact.

**Comment by Bathtor** [comment]
Thanks for your helpful answer. (I actually read it days ago in email, just forgot to come to Github to close the ticket.) I'm going to move forward then by setting the tolerance fairly low for my use-case and just deal with the small number of remaining special snowflake shapes :D
